version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: labdamd-postgres
    environment:
      POSTGRES_USER: labdamd
      POSTGRES_PASSWORD: pedro
      POSTGRES_DB: labdamd
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: labdamd-rabbitmq
    ports:
      - "5672:5672"    # porta AMQP (usada pelo Node.js)
      - "15672:15672"  # dashboard web (abre no navegador)
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

volumes:
  postgres_data:
